apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wedding-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:idoyo7/montstrap-manifest.git
    targetRevision: main
    path: wedding-invitation2/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: wedding-invitation
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
