apiVersion: autokuma.bigboot.dev/v1
kind: KumaEntity
metadata:
  name: study-nextra-stage
  namespace: study-nextra
spec:
  config:
    type: http
    name: study-nextra (stage)
    url: https://study-nextra.makgol.com
    interval: 60
    max_retries: 3
