apiVersion: v1
kind: Service
metadata:
  name: study-starlight-service
  namespace: study-starlight
spec:
  selector:
    app: study-starlight
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
