apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - monitor.yaml
images:
  - name: montkim9/invi2
    newTag: 9a0e2c
