apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autokuma-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 1Gi
