apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - monitor.yaml
images:
  - name: ghcr.io/idoyo7/study-starlight
    newTag: "7d73b4"
