apiVersion: v1
kind: Service
metadata:
  name: palworld-admin-service
  namespace: palworld
spec:
  selector:
    app: palworld-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
